rbac:
  create: true
  pspEnabled: true
  pspUseAppArmor: true
  namespaced: false
  extraRoleRules: []
  extraClusterRoleRules: []

serviceAccount:
  create: true
  name: ""
  nameTest: ""

replicas: 1

podDisruptionBudget: {}

deploymentStrategy:
  type: RollingUpdate

readinessProbe:
  httpGet:
    path: /api/health
    port: 3000

livenessProbe:
  httpGet:
    path: /api/health
    port: 3000
  initialDelaySeconds: 60
  timeoutSeconds: 30
  failureThreshold: 10

image:
  repository: grafana/grafana
  tag: 6.4.2
  pullPolicy: IfNotPresent

testFramework:
  enabled: true
  image:
    registry: docker.io
    repository: bats/bats
    tag: "0.4.0"
  securityContext: {}

securityContext:
  runAsUser: 472
  fsGroup: 472

extraConfigmapMounts: []

extraEmptyDirMounts: []

downloadDashboardsImage:
  repository: appropriate/curl
  tag: latest
  pullPolicy: IfNotPresent

downloadDashboards:
  env: {}

podPortName: grafana

service:
  type: NodePort
  port: 9000
  targetPort: 3000
  nodePort: 30007
  annotations: {}
  labels: {}
  portName: service

ingress:
  enabled: false
  annotations: {}
  labels: {}
  path: /
  hosts:
    - chart-example.local
  extraPaths: []
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

extraInitContainers: []

extraContainers: |
# - name: proxy
#   image: quay.io/gambol99/keycloak-proxy:latest
#   args:
#   - -provider=github
#   - -client-id=
#   - -client-secret=
#   - -github-org=<ORG_NAME>
#   - -email-domain=*
#   - -cookie-secret=
#   - -http-address=http://0.0.0.0:4181
#   - -upstream-url=http://127.0.0.1:3000
#   ports:
#     - name: proxy-web
#       containerPort: 4181

persistence:
  type: pvc
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  finalizers:
    - kubernetes.io/pvc-protection

initChownData:
  enabled: true
  image:
    repository: busybox
    tag: "1.30"
    pullPolicy: IfNotPresent
  resources: {}

adminUser: admin

admin:
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password

env: {}

envFromSecret: ""

envRenderSecret: {}

extraSecretMounts: []

extraVolumeMounts: []
plugins: []
datasources: {}

notifiers: {}

dashboardProviders: {}
dashboards: {}
dashboardsConfigMaps: {}

grafana.ini:
  paths:
    data: /var/lib/grafana/data
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
  grafana_net:
    url: https://grafana.net

ldap:
  enabled: false
  existingSecret: ""
  config: ""

smtp:
  existingSecret: ""
  userKey: "user"
  passwordKey: "password"

sidecar:
  image:
    registry: quay.io
    repository: kiwigrid/k8s-sidecar
    tag: 1.28.0
  imagePullPolicy: IfNotPresent
  resources: {}

  dashboards:
    enabled: false
    label: grafana_dashboard
    folder: /tmp/dashboards
    defaultFolderName: null
    searchNamespace: null
    provider:
      name: sidecarProvider
      orgid: 1
      folder: ''
      type: file
      disableDelete: false
  datasources:
    enabled: false
    label: grafana_datasource
    searchNamespace: null
